### ISSUE TITLE
Update to EquityDeservingGroup field

### ISSUE THREAD

**Issue by LoyerM** [commonapproach/AirtableBasicTier-Extension#20]
I've updated the previously named "hasDescription" to 'hasName". There were two fields called hasDescription and the companion module documentation calls for a hasName. 

This change may cause issues with import/export using the extension.

**Comment by MuriloDeltalyz** [comment]
Hi @LoyerM 

Can you confirm this change, please? I check the documentation in this link:

https://docs.google.com/document/d/1f1IFFdrc7PJyByNCipJicOh4E3WxkI68qx4KIUrszks/edit?tab=t.0

It is showing the hasDescription field yet.

![image](https://github.com/user-attachments/assets/cc3e929b-d59f-495a-bbf0-3e54f6ceb5ac)

**Comment by LoyerM** [comment]
I think I looked at the code list which is incorrect. I should have looked
at the correct class properties. I have corrected this in the base. Issue
resolved.

*Mikayla Loyer*

Manager, Business Integration

Common Approach to Impact Measurement
